global:
  # AWS, GCP, SCP, ...
  cloudPlatform: AWS
  aws:
    dbEndPoint: "hong-db.c2teww4mkk5s.ap-northeast-2.rds.amazonaws.com"
  usePrometheus: true
  nfType: "SMSF"

  commonLabels:
    product: "smsf"
    vendor: "uangel"

  serviceName:
    svc: "usmsf-svc"
    map: "usmsf-map-svc"
    dia: "usmsf-dia-svc"
    dia_hasvc: "ua-hasvc"
    mariadb: "umariadb"
    uccms: "usmsf-uccms"
    emagt: "emagt"
  port:
    db:
      mariadb: 3306
    map:
      container: 8080
    dia:
      container: 8080
      forSMSC: 3868
    uccms:
      servicePort: 9090
    emagt:
      http: 9292
      ws: 9393
    emgui: 9090
  smsf:
    nfId: "d1443c16-bf97-46c2-8633-d396161e911c"
    mcc: "450"
    mnc: "05"
    ipaddr:
      expose:
        svc:
          ipv4: ""
          ipv4ForExternalIP: ""
        nrfClient:
          ipv4: ""
          ipv4ForExternalIP: ""
    serverPort:
      forNFServer:
        http: 8001
        https: 8002
      forInternal:
        http: 8011
        https: 8012
      forConfigMgr:
        http: 8090
      forTrace:
        http: 8100
  dnsName:
    #zone: "5gsamsung.local"
    zone: "cluster.local"
  #nodeName: "iot-02"
  smscSim:
    clusterIP: "10.100.176.200"

  # Set to "" to not set timezone
  timezone: "Asia/Seoul"

  simNamespace: "coredev-usmsf-sim"
