apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- $dirpath := printf "configfiles/*.json" }}
  {{- range $path, $_ := .Files.Glob $dirpath }}
  {{ base $path }}: |-
  {{ $.Files.Get $path | nindent 4 }}
  {{- end }}

  logger.conf: |-
    loggers {
        root {
            level = {{ .Values.configmap.logger.logLevels.root | quote }}
            appender = [
                console
            ]
        }
    }
    
    appenders {
        console {
            format = "text"
            class = "Console"
            print-caller = true
        }
    }

  uccms.conf: |- 
    modules = [
        echolib.Defaults
        echolib.StartAllServer
        ulib.Defaults
        ulib.LimiterConfigurator

        mysqllib.Defaults

        uccms.DB
        uccms.MemCache
        uccms.APIServer
        uccms.APIServices
    ] ,

    logrus {
        config-file = "/app/config/logger.conf"
        watch-config = false 
    }

    limiter.conf-file = "/app/config/limiter.conf"

    apiServicePool {
        type = alarmPool
        pool-size = 10
        max-queueing-duration = 2s 
    }

    http-servers {
        uccms {
            host = 0.0.0.0 # uccms-specific
            port = 9090
            api = v1 # uccms-specific

            tls = false
            serve-for = internal
            # metric-registry = mgmt
            exec-context = apiServicePool 
            request-timeout = 2s
            limiter = internal 
        }
    }

    http-client {
        circuit-breaker {
            consecutiveErrors = 100
            interval = 10s
            baseEjectionTime = 3m

            maxPendingRequest = 4
        }
    }

    services {
        subscriptions {
            notif-timeout = 3s
            heartbeat-checker: {
                interval = 1m
                timeout = 90s
            }
        }
    }

    mysqlpool {
        type = alarmPool
        size = 20
    }

    mysql {
        driver : mysql
        host : ${?MANAGE_DB_HOST}
        user : root
        password : "root.123"
        dbname : uccms

        # common configurations for connector
        pool : mysqlpool
        query-timeout: 3s # default: 3s
        max-open-conns: 0
        max-idle-conns: 0
        max-conn-liftime: 0
    }

  limiter.conf: |- 
    configuration {
        limiters {
            internal {
                max-tps : 100
            }
        }
    }

