apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.name }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        version: v1
        {{- toYaml .Values.global.commonLabels | nindent 8 }}
    spec:
      {{- if .Values.global.nodeName }}
      nodeName: {{ .Values.global.nodeName }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: uccms
        image: {{ .Values.deployment.containers.uccms.image }}
        imagePullPolicy: {{ .Values.deployment.containers.uccms.imagePullPolicy }}
        {{- if .Values.resources }}
        resources: {{ toYaml .Values.deployment.containers.uccms.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /home/app/config
        ports:
        - containerPort: {{ .Values.deployment.containers.uccms.port }}
        env:
        - name: UCCMS_CONFIG_FILE
          value: /home/app/config/uccms.conf
        - name: LOGGER_CONFIG
          value: /home/app/config/logger.conf
        - name: MANAGE_DB_DRIVER
          value: "mysql"
        - name: MANAGE_DB_HOST
          {{- if (eq .Values.global.cloudPlatform "AWS") }}
          value: "{{ .Values.global.aws.dbEndPoint }}"
          {{- else }}
          value: "{{ .Values.global.serviceName.mariadb }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.port.db.mariadb }}"
          {{- end }}
        - name: MANAGE_DB_USER
          value: "root"
        - name: MANAGE_DB_PW
          value: "root.123"
        - name: MANAGE_DB_NAME
          value: "uccms"
        - name: MANAGE_SVC_PORT
          value: {{ .Values.deployment.containers.uccms.port | quote }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configmap.name }}
