apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.serviceName.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dish_smsf.name" . }}
    helm.sh/chart: {{ include "dish_smsf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: usmsf
  template:
    metadata:
      labels:
        app: usmsf
        version: v1
        {{- toYaml .Values.global.commonLabels | nindent 8 }}
    spec:
      {{- if .Values.global.nodeName }}
      nodeName: {{ .Values.global.nodeName }}
      {{- end }}
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: {{ .Values.deployment.volumes.config.name }}
        configMap:
          name: {{ .Values.configmap.name }}
      - name: log-volume
        emptyDir: {}
      - name: tcpdump 
        emptyDir: {}
      {{- if ne .Values.global.timezone "" }}
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.global.timezone }}
      {{- end }}

      hostAliases:
        {{- range $aliasIdx, $alias := .Values.deployment.hostAliases }}
        - ip: {{ $alias.ip | quote }}
          hostnames:
          {{- range $hostnameIdx, $hostname := $alias.hostnames }}
          - {{ $hostname | quote }}
          {{- end }}
        {{- end }}
    
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}

      containers:
      - name: redis-server
        image: {{ .Values.deployment.containers.redisServer.image }}
        imagePullPolicy: {{ .Values.deployment.containers.redisServer.imagePullPolicy }}
        ports:
         - containerPort: {{ .Values.deployment.containers.redisServer.containerPort }}

      - name: usmsf
        image: {{ .Values.deployment.containers.usmsf.image }}
        imagePullPolicy: {{ .Values.deployment.containers.usmsf.imagePullPolicy }}
        {{- if .Values.deployment.containers.usmsf.resources }}
        resources: {{ toYaml .Values.deployment.containers.usmsf.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.deployment.volumes.config.name }}
          mountPath: /home/app/config
        - name: {{ .Values.deployment.volumes.sharedData.name }}
          mountPath: /tmp
        - name: {{ .Values.deployment.volumes.log.name }}
          mountPath: /home/app/logs
        {{- if ne .Values.global.timezone "" }}
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
        ports:
        - containerPort: {{ .Values.global.smsf.serverPort.forNFServer.http }}
        - containerPort: {{ .Values.global.smsf.serverPort.forNFServer.https }}
        - containerPort: {{ .Values.global.smsf.serverPort.forInternal.http }}
        - containerPort: {{ .Values.global.smsf.serverPort.forConfigMgr.http }}
        env:
        - name: USMSF_HOME
          value: "/home/app"
        - name: USMSF_CONFIG_FILE
          value: "/home/app/config/usmsf.conf"
        - name: USMSF_FAILNOTI_ADDR
          value: http://{{ .Values.global.smsf.ipaddr.expose.svc.ipv4 }}:{{ .Values.global.smsf.serverPort.forNFServer.http }}
        - name: USMSF_FQDN
          value: {{ .Values.global.serviceName.svc }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}
        - name: SMS_STAT_DIR
          value: /tmp/stat
        - name: TRACE_HOME_ENV_NAME
          value: /tmp/trace
        # TODO EM_HOST value 변수화하자.
        - name: EM_HOST
          value: localhost:9090
        - name: CONF_POD_HOST
          value: {{ .Values.global.serviceName.uccms }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.port.uccms.servicePort }}
        - name: DIAMETER_POD_DOMAIN_NAME 
          value: "{{ .Values.global.serviceName.dia_hasvc }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}"
        - name: DIAMETER_POD_PORT
          value: "{{ .Values.global.port.dia.container }}"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- if eq .Values.deployment.containers.usmsf.useManualStart true }}
        command: ["sh", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        {{- end }}

        {{- if eq .Values.deployment.containers.usmsf.healthCheck.liveness.sendProbe true }}
        livenessProbe:
          httpGet:
            path: /live
            port: {{ .Values.configmap.usmsfConf.healthCheck.listenPort }}

          # 처음에 initialDelaySeconds 초 동안 기다렸다가 컨테이너가 살아있는지 검사한다.
          initialDelaySeconds: {{ .Values.deployment.containers.usmsf.healthCheck.liveness.initialDelaySeconds }}

          # initialDelaySeconds 초 이후부터 periodSeconds 초마다 컨테이너가 살아있는지 검사한다.
          periodSeconds: {{ .Values.deployment.containers.usmsf.healthCheck.liveness.periodSeconds }}
        {{- end }}

        {{- if eq .Values.deployment.containers.usmsf.healthCheck.readiness.sendProbe true }}
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.configmap.usmsfConf.healthCheck.listenPort }}

          # 처음에 initialDelaySeconds 초 동안 기다렸다가 컨테이너가 트래픽을 받을 준비가 되었는지 검사한다.
          initialDelaySeconds: {{ .Values.deployment.containers.usmsf.healthCheck.readiness.initialDelaySeconds }}

          # initialDelaySeconds 초 이후부터 periodSeconds 초마다 컨테이너가 트래픽을 받을 준비가 되었는지 검사한다.
          periodSeconds: {{ .Values.deployment.containers.usmsf.healthCheck.readiness.periodSeconds }}
        {{- end }}

      - name: emsubagt
        image: {{ .Values.deployment.containers.emsubagt.image }}
        imagePullPolicy: {{ .Values.deployment.containers.emsubagt.imagePullPolicy }}
        volumeMounts:
        - name: shared-data 
          mountPath: /tmp
        env:
        - name: EM_SERVICE
          value: {{ .Values.global.serviceName.emagt }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}
        - name: MY_SERVICE
          value: WEB_SERVICE
        - name: EM_HTTP_PORT
          value: {{ .Values.global.port.emagt.http | quote }}
        - name: EM_WS_PORT
          value: {{ .Values.global.port.emagt.ws | quote }}
        - name: MY_GROUP
          value: WEB_SERVICE
        - name: MYSQL_ADDR
          {{- if (eq .Values.global.cloudPlatform "AWS") }}
          value: "{{ .Values.global.aws.dbEndPoint }}"
          {{- else }}
          value: "{{ .Values.global.serviceName.mariadb }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}"
          {{- end }}
        - name: ENALBED_TRACE
          value: "true"
        - name: MMCD
          value: "false"

