apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.global.serviceName.dia_hasvc }}
  annotations:
    uangel.com/as-stateful-set: {{ .Values.global.serviceName.dia }}
spec:
  #type: {{ .Values.service.type | default "ClusterIP" }}
  clusterIP: None
  ports:
  - name: diameter
    port: {{ .Values.global.port.dia.forSMSC }}
  - name: http-nfserver
    port: {{ .Values.global.port.dia.container }}
    targetPort: 8080
    {{- if (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: usmsf-adif
    statefulset.kubernetes.io/pod-name: {{ .Values.global.serviceName.dia }}-0

