apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.global.serviceName.dia }}
spec:
  serviceName: "usmsf-adif"
  replicas: 2
  selector:
    matchLabels:
      app: usmsf-adif # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: usmsf-adif
        version: v1
        {{- toYaml .Values.global.commonLabels | nindent 8 }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10020"
        prometheus.io/scrape: "true"
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}

      containers:
      - name: usmsf-dia-svc
        image: {{ .Values.deployment.containers.diaSvc.image }}
        imagePullPolicy: {{ .Values.deployment.containers.diaSvc.imagePullPolicy }}
        volumeMounts:
        - name: shared-data
          mountPath: /tmp
        {{- if ne .Values.global.timezone "" }}
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
        env:
        - name: USMSF_HOME
          value: /home/app
        - name: TRACE_HOME_ENV_NAME
          value: /tmp/trace
#        command: ["bash", "-c", "--"]
#        args: ["while true; do sleep 30; done;"]
      - name: usmsf-httpif
        image: {{ .Values.deployment.containers.httpif.image }}
        imagePullPolicy: {{ .Values.deployment.containers.httpif.imagePullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /home/app/config
        - name: shared-data
          mountPath: /tmp
        {{- if ne .Values.global.timezone "" }}
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
        ports:
        # TODO
        - containerPort: 8080
        env:
        - name: USMSF_HOME
          value: /home/app
        - name: HTTPIF_CONFIG_FILE
          value: /home/app/config/httpif.conf
        - name: SVC_POD_HOST
          value: usmsf-svc-internal.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.smsf.serverPort.forInternal.http }}
        - name: TRACE_HOME_ENV_NAME
          value: /tmp/trace
        - name: EM_HOST
          value: localhost:{{ .Values.global.port.emgui }}
        - name: CONF_POD_HOST
          value: usmsf-uccms.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}:{{ .Values.global.port.uccms.servicePort }}
        - name: MY_SERVICE_TYPE
          value: "DIAMETER"
        - name: CDR_DIR
          value: /tmp/cdr
        {{- if eq .Values.deployment.containers.httpif.useManualStart true }}
        command: ["sh", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        {{- end }}
      - name: usmsf-adif
        image: {{ .Values.deployment.containers.adif.image }}
        imagePullPolicy: {{ .Values.deployment.containers.adif.imagePullPolicy }}
        command :
        - bash
        - -c
        - |
          echo "$MY_POD_NAME"
          echo "$MY_POD_IP"
          hostname
          mkdir -p ${UCCMS_DATA_HOME}/backup
          rm -rf ${UASYS_HOME}/data/adif.conf
          ln -s ${INIT_CONF_HOME}/adif.conf ${UASYS_HOME}/data/adif.conf
          ${UASYS_HOME}/bin/adif-ha-run.sh
        volumeMounts:
        - name: usmsf-adif-conf-volume
          mountPath: /tmp/usmsf-adif-conf
        - name: uccms-data-volume
          mountPath: /tmp/uccms-data
        - name: log-volume
          mountPath: /home/app/HOME/log
        {{- if ne .Values.global.timezone "" }}
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
        env:
        - name: MY_POD_NAME 
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP 
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ACTIVE_SERVICE_NAME 
          value: "ua-hasvc" 
        - name: ACTIVE_CHECK_PERIOD 
          value: "1"
        - name: ADIF_CONFIG_FILE
          value: /home/app/HOME/data/adif.conf
        - name: INIT_CONF_HOME
          value: "/tmp/usmsf-adif-conf"
        - name: UCCMS_DATA_HOME
          value: "/tmp/uccms-data"
        - name: CLICOLOR_FORCE
          value: "1"
        #command: ["sh", "-c", "--"]
        #args: ["while true; do sleep 30; done;"]
      - name: emsubagt
        image: {{ .Values.deployment.containers.emsubagt.image }}
        imagePullPolicy: {{ .Values.deployment.containers.emsubagt.imagePullPolicy }}
        volumeMounts:
        - name: shared-data 
          mountPath: /tmp
        env:
        - name: EM_SERVICE
          value: {{ .Values.global.serviceName.emagt }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}
        - name: MY_SERVICE
          value: MAP_SERVICE
        - name: EM_HTTP_PORT
          value: {{ .Values.global.port.emagt.http | quote }}
        - name: EM_WS_PORT
          value: {{ .Values.global.port.emagt.ws | quote }}
        - name: MY_GROUP
          value: MAP_SERVICE
        - name: MYSQL_ADDR
          {{- if (eq .Values.global.cloudPlatform "AWS") }}
          value: "{{ .Values.global.aws.dbEndPoint }}"
          {{- else }}
          value: "{{ .Values.global.serviceName.mariadb }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}"
          {{- end }}
        - name: ENALBED_TRACE
          value: "true"
        - name: MMCD
          value: "false"
      - name: uccms-agent
        image: {{ .Values.deployment.containers.uccmsAgent.image }}
        imagePullPolicy: {{ .Values.deployment.containers.uccmsAgent.imagePullPolicy }}
        #command: ["sh", "-c", "--"]
        #args: ["while true; do sleep 30; done;"]
        volumeMounts:
        - name: usmsf-adif-conf-volume
          mountPath: /tmp/usmsf-adif-conf
        - name: uccms-data-volume
          mountPath: /tmp/uccms-data
        - name: log-volume
          mountPath: /tmp/log
        - name: usmsf-uccms-conf-volume
          mountPath: /tmp/usmsf-uccms-conf
        - name: usmsf-uccms-meta-volume
          mountPath: /tmp/usmsf-uccms-meta
        {{- if ne .Values.global.timezone "" }}
        - name: tz-config
          mountPath: /etc/localtime
        {{- end }}
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: UASYS_HOME
          value: "/tmp/usmsf-adif-conf"
        - name: AGENT_HOME
          value: "/tmp/usmsf-adif-conf"
        - name: AGENT_CONFIG
          value: "/tmp/usmsf-adif-conf/uccms-agent.conf"
        - name: INIT_CONF_HOME
          value: "/tmp/usmsf-adif-conf"
        - name: UCCMS_DATA_HOME
          value: "/tmp/uccms-data"
        - name: LOG_HOME
          value: "/tmp/log"
        - name: UCCMS_AGENT_HOST
          value: "0.0.0.0"
        - name: UCCMS_AGENT_PORT
          value: "11090"
        - name: UCCMS_AGENT_CALLBACK_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: UCCMS_AGENT_CALLBACK
          value: "$(UCCMS_AGENT_CALLBACK_IP):$(UCCMS_AGENT_PORT)"
#        command: ["sh", "-c", "--"]
#        args: ["while true; do sleep 30; done;"]

      volumes:
      - name: usmsf-adif-conf-volume
        configMap:
          name: {{ .Values.configmap.names.adif }}
      - name: uccms-data-volume
        emptyDir: {}
      - name: log-volume
        emptyDir: {}
      - name: shared-data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: {{ .Values.configmap.names.if }}
      - name: usmsf-uccms-conf-volume
        configMap:
          name: {{ .Values.configmap.names.uccmsConf }}
      - name: usmsf-uccms-meta-volume
        configMap:
          name: {{ .Values.configmap.names.uccmsMeta }}
      {{- if ne .Values.global.timezone "" }}
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.global.timezone }}
      {{- end }}
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w kernel.msgmax=65536
          sysctl -w kernel.msgmni=80000
          sysctl -w kernel.msgmnb=536862720
          sysctl -w net.ipv4.tcp_mem="8388608 8388608 10485760"
        securityContext:
          privileged: true
---
