# Default values for dish-smsf-dia.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

#resources:
#  limits:
#    cpu: 2000m
#    memory: 2048Mi
#  requests:
#    cpu: 2000m
#    memory: 2048Mi

#imagePullSecrets:
#- name: harbor-secret

nodeSelector: {}

tolerations: []

affinity: {}

service:
  #type: NodePort
  type: ClusterIP
  #nodePort: 31234

deployment:
  containers:
    diaSvc:
      image: camel.uangel.com:5000/dia_svc:latest
      imagePullPolicy: IfNotPresent
      useManualStart: false
    adif:
      image: camel.uangel.com:5000/adif:3.0.0
      imagePullPolicy: Always
      useManualStart: false
    emsubagt:
      image: camel.uangel.com:5000/emsubagt:latest
      imagePullPolicy: Always
      useManualStart: false
    httpif:
      image: camel.uangel.com:5000/usmsf-httpif:latest
      imagePullPolicy: IfNotPresent
      useManualStart: false
    uccmsAgent:
      image: camel.uangel.com:5000/uccms-sb-agent-cmd:latest
      imagePullPolicy: IfNotPresent
      useManualStart: false

configmap:
  names:
    adif: "usmsf-adif-conf"
    if: "usmsf-if-conf"
    uccmsMeta: "usmsf-dia-uccms-meta"
    uccmsConf: "usmsf-dia-uccms-conf"
  adifConf:
    sections:
      adif:
        activeStandby: "false"
      udifWorker:
        threadCount: 4
  udiaConfXml:
    useIp6: "no"
  httpifLogger:
    logLevels:
      root: "ERROR"
      com_uangel: "ERROR"
      samsung:
        fault: "ERROR"
        selfdiag: "ERROR"
        reset: "ERROR"
        init: "ERROR"
        console: "ERROR"
        error: "ERROR"
        event: "ERROR"
        info: "ERROR"

