apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.serviceName.emagt }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.service.emagt.name }}
    {{- toYaml .Values.global.commonLabels | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.emagt.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.emagt.name }}
        version: v1
        {{- toYaml .Values.global.commonLabels | nindent 8 }}
    spec:
      {{- if .Values.global.nodeName }}
      nodeName: {{ .Values.global.nodeName }}
      {{- end }}
      volumes:
      - name: shared-data
        emptyDir: {}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: emagt
        image: {{ .Values.deployment.containers.emagt.image }}
        imagePullPolicy: {{ .Values.deployment.containers.emagt.imagePullPolicy }}
        {{- if .Values.deployment.containers.emagt.resources }}
        resources: {{ toYaml .Values.deployment.containers.emagt.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.global.port.emagt.http }}
        - containerPort: {{ .Values.global.port.emagt.ws }}
        - containerPort: 8080
        env:
        - name: MYSQL_ADDR
          {{- if (eq .Values.global.cloudPlatform "AWS") }}
          value: "{{ .Values.global.aws.dbEndPoint }}"
          {{- else }}
          value: "{{ .Values.global.serviceName.mariadb }}.{{ .Release.Namespace }}.svc.{{ .Values.global.dnsName.zone }}"
          {{- end }}
        - name: SUPPORT_EXPORTER
          value: "true"
